<?php


    namespace blackpanda\tron;

    use Illuminate\Foundation\Support\Providers\EventServiceProvider as ServiceProvider;

    class TronEventServiceProvider extends ServiceProvider
    {
        protected $listen = [];


        public function boot()
        {
            parent::boot(); // TODO: Change the autogenerated stub
        }


    }
